id: I855BFF6A
legacy_id: P003306
ocr_import_info:
  bdrc_scan_id: W1KG26091
  source: bdrc
  ocr_info:
    timestamp: '2020-04-01T02:48:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T14:32:50.394336+00:00'
last_modified: 2022-08-31 22:32:57.128347
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG26091
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG26091
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མ་བཅོས་དངོས་འབྲེལ་བརྗོད་པ་དུས་ཀྱི་མེ་ལྕེ།
  author: གདོང་ཐོག་བསྟན་པའི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.8984849589972024
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I1KG26316:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG26316
      total_pages: 160
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG26316.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8984849589972024
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
