id: P003306
initial_creation_type: ocr
created_at: 1/04/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG26091
  title: མ་བཅོས་དངོས་འབྲེལ་བརྗོད་པ་དུས་ཀྱི་མེ་ལྕེ།
  author: ''
  volumes:
    cc60d33032054d22997c0ce4c70a01c7:
      image_group_id: I1KG26316
      title: ''
      volume_number: 1
      total_pages: 160
      base_file: v001.txt
